spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drones
    username: youruser
    password: yourpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
